import { NgModule } from '@angular/core';
import {	MatAutocompleteModule,
					MatButtonModule, 
					MatCardModule, 
					MatCheckboxModule,
					MatChipInputEvent,
					MatChipsModule,
					MatDatepickerModule,
					MatDialogModule,
					MatExpansionModule,
					MatFormFieldModule,
					MatGridListModule,
					MatIconModule,
					MatInputModule,
					MatListModule,
					MatMenuModule,
					MatNativeDateModule,
					MatProgressSpinnerModule,
					MatRadioModule,
					MatTableModule,
					MatToolbarModule,
					MatTooltipModule,
					MatSelectModule,
					MatSlideToggleModule } from '@angular/material';

@NgModule({
  imports: [
  	MatAutocompleteModule,
		MatButtonModule, 
		MatCardModule, 
		MatCheckboxModule, 
		MatChipsModule,
		MatDatepickerModule,
		MatDialogModule,
		MatExpansionModule,
		MatFormFieldModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatTableModule,
		MatToolbarModule,
		MatTooltipModule,
		MatSelectModule,
		MatSlideToggleModule
  ],
  exports: [
  	MatAutocompleteModule,
  	MatButtonModule, 
		MatCardModule, 
		MatCheckboxModule,
		MatChipsModule,
		MatDatepickerModule,
		MatDialogModule,
		MatExpansionModule,
		MatFormFieldModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatTableModule,
		MatToolbarModule,
		MatTooltipModule,
		MatSelectModule,
		MatSlideToggleModule
	],
  declarations: [],
})
export class AngularMaterialModule { }